[package]
name = "padsynth"
version = "0.1.0"
authors = ["nyanpasu64 <nyanpasu64@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
hound = "3.4.0"
realfft = "0.3.0"
rustfft = "4.0.0"
structopt = { version = "0.3.20", default-features = false }
